target_feature: class

test_size_params: 0.20




classifier__n_estimators: 
  start: 10 
  stop: 1000 
  num: 500

classifier__max_depth: 
  start : 1 
  stop : 100 
  num : 50

classifier__learning_rate: [0.05, 0.3]

preprocessor__num__imputer__strategy : ['mean', 'median']
preprocessor__num__drop_coluns_nan__max_range_null : [0.8,0.7,0.6]


n_inter_params: 15
error_score_params: 0
verbose_params: 3
n_jobs_params: -1


#Featreu Selection

classifier_FeatureSelector: classifier
kfold_FeatureSelector: 5
features_to_get_params: 10